### ISSUE TITLE
Seems to hang sometimes

### ISSUE THREAD

**Issue by samuelli** [samuelli/bot-render#48]
screenshot/https://fonts.google.com/?width=1280&height=1299 still hung after 85s. No errors, so something async never resolved.

**Comment by paales** [comment]
HI there! Just testing it out, seems to work pretty well. I am running into a problem as the above. On our new homepage we have a video that starts playing immediately. It seems that it is waiting for the video to fully play out before it can output something (since it is streaming in the video).

url: https://reachdigital-b332f.appspot.com/
